// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApBV8Bx_65PeRNpNps0hgGhJppBRRBdn0',
    appId: '1:292925185480:web:c2a4071715e25e6de274fd',
    messagingSenderId: '292925185480',
    projectId: 'contactapp-64acc',
    authDomain: 'contactapp-64acc.firebaseapp.com',
    storageBucket: 'contactapp-64acc.appspot.com',
    measurementId: 'G-8R90S74VVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhf-J30yUWMN8HyrlONzC9ohY0O4mv8uI',
    appId: '1:292925185480:android:50709cd21cb67130e274fd',
    messagingSenderId: '292925185480',
    projectId: 'contactapp-64acc',
    storageBucket: 'contactapp-64acc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd0VYUXtzm1UNwJIfNXdIkNhkvt5neWCI',
    appId: '1:292925185480:ios:42c2f8c6cd8a3a50e274fd',
    messagingSenderId: '292925185480',
    projectId: 'contactapp-64acc',
    storageBucket: 'contactapp-64acc.appspot.com',
    iosBundleId: 'com.example.contactApp',
  );
}
